### ISSUE TITLE
Panzerschreck

### ISSUE THREAD

**Issue by BCDeshiG** [hellomotolegacy/requiem-clean#3]
Right now it is derped since it doesn't have explosive bullets.

**Comment by hellomotolegacy** [comment]
This (along with Mustang & Sally) has been fixed.

**Comment by hellomotolegacy** [comment]
This (along with Mustang & Sally) has been fixed.

**Comment by hellomotolegacy** [comment]
This (along with Mustang & Sally) has been fixed.
